### ISSUE TITLE
private channelでmark as readがきかない

### ISSUE THREAD

**Issue by tazu-yyy** [TazuKongari/Slack-Stream#40]
```
Error: channel_not_found
    at handleHttpResponse (C:\Users\tazuke\electron\github\Slack-Stream\node_modules\@slack\client\lib\clients\transports\call-transport.js:105:17)
    at handleTransportResponse (C:\Users\tazuke\electron\github\Slack-Stream\node_modules\@slack\client\lib\clients\transports\call-transport.js:155:19)
    at apply (C:\Users\tazuke\electron\github\Slack-Stream\node_modules\lodash\lodash.js:499:17)
    at wrapper (C:\Users\tazuke\electron\github\Slack-Stream\node_modules\lodash\lodash.js:5356:16)
    at Request.handleRequestTranportRes (C:\Users\tazuke\electron\github\Slack-Stream\node_modules\@slack\client\lib\clients\transports\request.js:20:5)
    at apply (C:\Users\tazuke\electron\github\Slack-Stream\node_modules\lodash\lodash.js:499:17)
    at Request.wrapper [as _callback] (C:\Users\tazuke\electron\github\Slack-Stream\node_modules\lodash\lodash.js:5356:16)
    at Request.self.callback (C:\Users\tazuke\electron\github\Slack-Stream\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\tazuke\electron\github\Slack-Stream\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\tazuke\electron\github\Slack-Stream\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
```

**Comment by tazu-yyy** [comment]
https://api.slack.com/methods/groups.mark

**Comment by tazu-yyy** [comment]
test
